### ISSUE TITLE
GTAXLOC.WLEVC6,  GTAXWGT.WLEVC6がない

### ISSUE THREAD

**Issue by kanonundgigue** [wm-ytakano/gtool3-axis#1]
MATSIROの6層レイヤーが含まれていない。

**Comment by wm-ytakano** [comment]
@kanonundgigue プルリクでもメール添付でもいいので、データを頂ければ追加します。

**Comment by kanonundgigue** [comment]
@wm-ytakano Authentication failでプルリクに失敗したのでこちらをお願いします。
https://drive.google.com/drive/folders/1KllWCAHsCJ8k20GN9nFxBCAUVoT3NhoC?usp=sharing

**Comment by wm-ytakano** [comment]
ありがとうございます。追加しました。
